
language: fsharp
mono:
  - latest

before_install:
  - sudo apt-get update
  - sudo apt-get install -y nuget

solution: base/eLyKseeR-base.Linux.sln
install:
  - nuget restore -PackagesDirectory packages packages.config
  - nuget restore -PackagesDirectory packages UT/packages.config
script:
  - sn -k base/eLyKseeR.snk
  - sn -k native/eLyKseeR-native.snk
  - sn -k UT/ut.snk

  - msbuild /t:clean /p:Configuration="Debug" /p:Platform="Any CPU" base/eLyKseeR-base.Linux.sln
  - msbuild /p:Configuration="Debug" /p:Platform="Any CPU" base/eLyKseeR-base.Linux.sln

  - mono packages/NUnit.ConsoleRunner.3.10.0/tools/nunit3-console.exe UT/bin/Debug/UT.exe

