
language: csharp
mono:
  - latest

solution: base/eLyKseeR-base.Linux.sln
script:
  - nuget restore -PackagesDirectory packages packages.config
  - nuget restore -PackagesDirectory packages UT/packages.config
  - git submodule update --remote
  - cd ext/elykseer-crypto; ./build.Linux.jenkins.sh
  - cd ../..
  - cd ext/prngsharp.git/; ./build.Linux.jenkins.sh
  - cd ../..
  - sn -k base/eLyKseeR.snk
  - sn -k native/eLyKseeR-native.snk
  - sn -k UT/ut.snk

  - msbuild /t:clean /p:Configuration="Debug" /p:Platform="Any CPU" base/eLyKseeR-base.Linux.sln
  - msbuild /p:Configuration="Debug" /p:Platform="Any CPU" base/eLyKseeR-base.Linux.sln

  - mono packages/NUnit.ConsoleRunner.3.10.0/tools/nunit3-console.exe UT/bin/Debug/UT.exe

